### ISSUE TITLE
Cannot install with pip

### ISSUE THREAD

**Issue by GoogleCodeExporter** [niltonvolpato/python-progressbar#42]
```
pip3 install progressbar

Collecting progressbar
  Using cached progressbar-2.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/w_/6ddpl57d1hx5m1m_nbhwd3qw0000gn/T/pip-build-3lzw6hbv/progressbar/setup.py", line 5, in <module>
        import progressbar
      File "/private/var/folders/w_/6ddpl57d1hx5m1m_nbhwd3qw0000gn/T/pip-build-3lzw6hbv/progressbar/progressbar/__init__.py", line 59, in <module>
        from progressbar.widgets import *
      File "/private/var/folders/w_/6ddpl57d1hx5m1m_nbhwd3qw0000gn/T/pip-build-3lzw6hbv/progressbar/progressbar/widgets.py", line 121, in <module>
        class FileTransferSpeed(Widget):
      File "/Users/mortenb/Downloads/test/env/bin/../lib/python3.4/abc.py", line 133, in __new__
        cls = super().__new__(mcls, name, bases, namespace)
    ValueError: 'format' in __slots__ conflicts with class variable
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/w_/6ddpl57d1hx5m1m_nbhwd3qw0000gn/T/pip-build-3lzw6hbv/progressbar

```

Original issue reported on code.google.com by `mort...@gmail.com` on 11 Apr 2015 at 11:16

**Comment by avengerpenguin** [comment]
Has this fix been released yet?

**Comment by berlotto** [comment]
@avengerpenguin not yet

**Comment by yarikoptic** [comment]
not released by I believe fixed in master in regard of compatibility with recent python3s

```shell
$> virtualenv --python=python3 venv           
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/venv/bin/python3
Not overwriting existing python script /tmp/venv/bin/python (you must use /tmp/venv/bin/python3)
Installing setuptools, pkg_resources, pip, wheel...source done.
2 11107.....................................:Wed 25 May 2016 11:35:29 PM EDT:.
hopa:/tmp
$> source venv/bin/activate
(venv) 2 11108.....................................:Wed 25 May 2016 11:35:35 PM EDT:.
hopa:/tmp
$> pip install https://github.com/datalad/python-progressbar/archive/master.zip
Collecting https://github.com/datalad/python-progressbar/archive/master.zip
  Downloading https://github.com/datalad/python-progressbar/archive/master.zip
     \ 20kB 1.1MB/s
Installing collected packages: progressbar
  Running setup.py install for progressbar ... done
Successfully installed progressbar-2.3
(venv) 2 11109.....................................:Wed 25 May 2016 11:35:47 PM EDT:.
hopa:/tmp
$> which python
/tmp/venv/bin/python
(venv) 2 11110.....................................:Wed 25 May 2016 11:35:54 PM EDT:.
hopa:/tmp
$> python --version
Python 3.5.1+
(venv) 2 11111.....................................:Wed 25 May 2016 11:35:57 PM EDT:.
hopa:/tmp
$> pip --version
pip 8.1.2 from /tmp/venv/local/lib/python3.5/site-packages (python 3.5)
```

**Comment by fenchu** [comment]
Please Gentlemen, Hit this bug today 1.5 year later. Still not released. Master works. python3 is taking over the world. Thanks

**Comment by yarikoptic** [comment]
I just switched to tqdm

**Comment by MiX1964** [comment]
I don't know if still relevant but I experienced the same issue while trying to pip install progressbar.
Found a fix in https://github.com/niltonvolpato/python-progressbar/issues/54
pip3 install progressbar33 worked for me
